---
# file: webtty.yml

- name: Set up WebUI Shell
  local_action: true
  hosts: local
  vars_files:
    - vars/nginx.yml
    - vars/jailed.yml
  roles:
    - role: certificates
    - role: geerlingguy.docker
    - role: webtty
    - role: geerlingguy.nginx
    - role: docker-jail