---
# file: webtty.yml

- name: Set up WebUI Shell
  hosts: local
  vars_files:
    - vars/nginx.yml
  vars:
    - ssh_jailed_users: ["max", "mellanie"]
  roles:
    - role: certificates
    - role: geerlingguy.docker
    - role: webtty
    - role: geerlingguy.nginx
    - role: docker-jail