---
# file: webtty.yml

- name: Set up WebUI Shell
  hosts: local
  vars_files:
    - vars/nginx.yml
    - vars/jailed.yml
  roles:
    - role: certificates
    - role: geerlingguy.docker
    - role: webtty
    - role: geerlingguy.nginx
    - role: docker-jail

  tasks:
  
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
