FROM debian:bookworm
LABEL purpose=jail
RUN apt update && apt install -y \
    procps \
    nano \
    vim \
    sudo \
    && rm -rf /var/list/apt/lists/*

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers