FROM debian:bookworm
LABEL purpose=jail
RUN apt update && apt install -y \
    procps \
    nano \
    vim \
    sudo \
    less \
    python3 \
    && rm -rf /var/list/apt/lists/*

RUN echo '%users ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Make it a bit fancy
RUN <<EOF cat >> /etc/profile
export PS1="🐳 \u:\W# "
export LS_OPTIONS='--color=auto'
eval "$(dircolors)"
alias ls='ls $LS_OPTIONS'
EOF