---
# - name: Create a network with custom IPAM config
#   docker_network:
#     name: 
#     ipam_config:
#       - subnet: 172.3.27.0/24
#         gateway: 172.3.27.2
#         iprange: 172.3.27.0/26
#         aux_addresses:
#           host1: 172.3.27.3
#           host2: 172.3.27.4

- name: Run Webtty container
  docker_container:
    name: webtty
    state: started
    network_mode: host
    image: wettyoss/wetty
    command: 
      - wetty
      - --base=/
      - --ssh-host={{ docker_bridge.network.IPAM.Config[0].Gateway }}
