---

- name: Get infos on network
  docker_network_info:
    name: bridge
  register: docker_bridge

- name: Create Webtty systemd service file
  ansible.builtin.template:
    src: templates/webtty.service.j2
    dest: /etc/systemd/system/webtty.service

- name: Enable Webtty unit
  ansible.builtin.systemd_service:
    name: webtty
    state: started
    enabled: true
    daemon_reload: true
