---

- name: Run Webtty container
  docker_container:
    name: webtty
    state: started
    ports:
      - 3000:3000
    image: wettyoss/wetty
    command: 
      - wetty
      - --base=/
      - --ssh-host={{ docker_bridge.network.IPAM.Config[0].Gateway }}
