---

- name: Get infos on network
  docker_network_info:
    name: bridge
  register: docker_bridge

- name: Run Webtty container
  docker_container:
    name: webtty
    state: started
    image: wettyoss/wetty
    command: 
      - wetty
      - --base=/
      - --ssh-host={{ docker_bridge.network.IPAM.Config[0].Gateway }}
  when: docker_bridge.exists